language: python
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install nose

seript:
  - nosetests -v --with-coverage-package=api

after_success:
  - coveralls